parser: babel-eslint
env:
  browser: true
  jest: true
plugins:
  - react
  - jsx-a11y
  - import
  - prettier
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
  global-require: off
  import/prefer-default-export: off
  no-unused-expressions:
    - error
    - allowTaggedTemplates: true
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/label-has-for: off
  arrow-parens:
    - error
    - as-needed
  no-trailing-spaces:
    - error
    - skipBlankLines: false
  comma-dangle:
    - error
    - only-multiline
  implicit-arrow-linebreak: off
